[package]
name = "wasmtime-shim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
spec = { path = "../spec" }
wasmtime = "3.0.0"
wasmtime-wasi = "3.0.0"
